package com.agendashows.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CantorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCantorAllPropertiesEquals(Cantor expected, Cantor actual) {
        assertCantorAutoGeneratedPropertiesEquals(expected, actual);
        assertCantorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCantorAllUpdatablePropertiesEquals(Cantor expected, Cantor actual) {
        assertCantorUpdatableFieldsEquals(expected, actual);
        assertCantorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCantorAutoGeneratedPropertiesEquals(Cantor expected, Cantor actual) {
        assertThat(actual)
            .as("Verify Cantor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCantorUpdatableFieldsEquals(Cantor expected, Cantor actual) {
        assertThat(actual)
            .as("Verify Cantor relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getGeneroMusical()).as("check generoMusical").isEqualTo(expected.getGeneroMusical()))
            .satisfies(a -> assertThat(a.getBio()).as("check bio").isEqualTo(expected.getBio()))
            .satisfies(a -> assertThat(a.getFotoPerfil()).as("check fotoPerfil").isEqualTo(expected.getFotoPerfil()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCantorUpdatableRelationshipsEquals(Cantor expected, Cantor actual) {
        // empty method
    }
}
