package com.agendashows.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShowAllPropertiesEquals(Show expected, Show actual) {
        assertShowAutoGeneratedPropertiesEquals(expected, actual);
        assertShowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShowAllUpdatablePropertiesEquals(Show expected, Show actual) {
        assertShowUpdatableFieldsEquals(expected, actual);
        assertShowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShowAutoGeneratedPropertiesEquals(Show expected, Show actual) {
        assertThat(actual)
            .as("Verify Show auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShowUpdatableFieldsEquals(Show expected, Show actual) {
        assertThat(actual)
            .as("Verify Show relevant properties")
            .satisfies(a -> assertThat(a.getLocal()).as("check local").isEqualTo(expected.getLocal()))
            .satisfies(a -> assertThat(a.getDataShow()).as("check dataShow").isEqualTo(expected.getDataShow()))
            .satisfies(a -> assertThat(a.getHorarioInicio()).as("check horarioInicio").isEqualTo(expected.getHorarioInicio()))
            .satisfies(a -> assertThat(a.getObservacoes()).as("check observacoes").isEqualTo(expected.getObservacoes()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShowUpdatableRelationshipsEquals(Show expected, Show actual) {
        assertThat(actual)
            .as("Verify Show relationships")
            .satisfies(a -> assertThat(a.getCantor()).as("check cantor").isEqualTo(expected.getCantor()));
    }
}
